exports.getGenre = () => { return new Map([
        ['Biography','1'],
        ['Film Noir','2'],
        ['Game Show','3'],
        ['Musical','4'],
        ['Sport','5'],
        ['Short','6'],
        ['Adult','7'],
        ['Adventure', '12'],
        ['Fantasy', '14'],
        ['Animation', '16'],
        ['Drama', '18'],
        ['Horror', '27'],
        ['Action', '28'],
        ['Comedy', '35'],
        ['Historical', '36'],
        ['Western', '37'],
        ['Thriller', '53'],
        ['Crime', '80'],
        ['Documentary', '99'],
        ['Science Fiction', '878'],
        ['Mystery','9648'],
        ['Musical','10402'],
        ['Romance','10749'],
        ['Family','10751'],
        ['War','10752'],
        ['News','10763'],
        ['Reality','10764'],
        ['Talk Show','10767']
    ]);
}