exports.getGenreNum = () => { return new Map([
        ['Biography','1'],
        ['Film Noir','2'],
        ['Game Show','3'],
        ['Musical','4'],
        ['Sport','5'],
        ['Short','6'],
        ['Adult','7'],
        ['Adventure', '12'],
        ['Fantasy', '14'],
        ['Animation', '16'],
        ['Drama', '18'],
        ['Horror', '27'],
        ['Action', '28'],
        ['Comedy', '35'],
        ['Historical', '36'],
        ['Western', '37'],
        ['Thriller', '53'],
        ['Crime', '80'],
        ['Documentary', '99'],
        ['Science Fiction', '878'],
        ['Mystery','9648'],
        ['Musical','10402'],
        ['Romance','10749'],
        ['Family','10751'],
        ['War','10752'],
        ['News','10763'],
        ['Reality','10764'],
        ['Talk Show','10767']
    ]);
}

exports.getGenre = () => { return new Map([
        [1,"Biography"],
        [10402,"Music"],
        [10749,"Romance"],
        [10751,"Family"],
        [10752,"War"],
        [10763,"News"],
        [10764,"Reality"],
        [10767,"Talk Show"],
        [12,"Adventure"],
        [14,"Fantasy"],
        [16,"Animation"],
        [18,"Drama"],
        [2,"Film Noir"],
        [27,"Horror"],
        [28,"Action"],
        [3,"Game Show"],
        [35,"Comedy"],
        [36,"History"],
        [37,"Western"],
        [4,"Musical"],
        [5,"Sport"],
        [53,"Thriller"],
        [6,"Short"],
        [7,"Adult"],
        [80,"Crime"],
        [878,"Science Fiction"],
        [9648,"Mystery"],
        [99,"Documentary"]
    ]);
}